CREATE DATABASE testdb;

CREATE TABLE PLAN(PLANID INT, PLAN_NAME VARCHAR(20), PRIMARY KEY(PLANID));
CREATE TABLE USERS(USERID INT, USERNAME VARCHAR(20), PASSWORD VARCHAR(20), EMAIL VARCHAR(20), PLANID INT, PRIMARY KEY(USERID), FOREIGN KEY(PLANID) REFERENCES PLAN(PLANID));

CREATE TABLE GENRE(GENREID INT, GENRE_NAME VARCHAR(20), PRIMARY KEY(GENREID));
CREATE TABLE STUDIO(STUDIOID INT, STUDIO_NAME VARCHAR(20), PRIMARY KEY(STUDIOID), FOREIGN KEY(GENREID) REFERENCES GENRE(GENREID));
CREATE TABLE TRAILER(TRAILERID INT, TRAILERURL VARCHAR(20), PRIMARY KEY(TRAILERID));
CREATE TABLE POSTER(POSTERID INT, POSTERURL VARCHAR(20), PRIMARY KEY(POSTERID));
CREATE TABLE MOVIE(MOVIEID INT, MOVIE_NAME VARCHAR(20), MOVIE_YEAR INT, MOVIE_DESCRIPTION VARCHAR(200), GENREID INT, STUDIOID INT, TRAILERID INT, POSTERID INT, PRIMARY KEY(MOVIEID), FOREIGN KEY(GENREID) REFERENCES GENRE(GENREID), FOREIGN KEY(STUDIOID) REFERENCES STUDIO(STUDIOID), FOREIGN KEY(TRAILERID) REFERENCES TRAILER(TRAILERID), FOREIGN KEY(POSTERID) REFERENCES POSTER(POSTERID));

SELECT * FROM MOVIE;
SELECT * FROM USERS;

