

CREATE TABLE `USERS`(
    `USER_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `PLAN_ID` INT NOT NULL
);
ALTER TABLE
    `USERS` ADD PRIMARY KEY `users_user_id_primary`(`USER_ID`);
CREATE TABLE `PLAN`(
    `PLAN_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PLAN_NAME` VARCHAR(255) NOT NULL
);
ALTER TABLE
    `PLAN` ADD PRIMARY KEY `plan_plan_id_primary`(`PLAN_ID`);
CREATE TABLE `MOVIE`(
    `MOVIE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `TITLE` VARCHAR(255) NOT NULL,
    `DESCRIPTION` TEXT NOT NULL,
    `RELEASE_DATE` DATE NOT NULL,
    `GENRE_ID` VARCHAR(255) NOT NULL,
    `RATING` INT NOT NULL,
    `POSTER_ID` INT NOT NULL,
    `TRAILER_ID` INT NOT NULL
);
ALTER TABLE
    `MOVIE` ADD PRIMARY KEY `movie_movie_id_primary`(`MOVIE_ID`);
CREATE TABLE `STUDIO`(
    `STUDIO_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `STUDIO_NAME` VARCHAR(255) NOT NULL
);
ALTER TABLE
    `STUDIO` ADD PRIMARY KEY `studio_studio_id_primary`(`STUDIO_ID`);
CREATE TABLE `GENRE`(
    `GENRE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `GENRE_NAME` VARCHAR(255) NOT NULL,
    `STUDIO_ID` INT NOT NULL
);
ALTER TABLE
    `GENRE` ADD PRIMARY KEY `genre_genre_id_primary`(`GENRE_ID`);
ALTER TABLE
    `GENRE` ADD UNIQUE `genre_studio_id_unique`(`STUDIO_ID`);
CREATE TABLE `TRAILER`(
    `TRAILER_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `TRAILER_URL` VARCHAR(255) NOT NULL
);
ALTER TABLE
    `TRAILER` ADD PRIMARY KEY `trailer_trailer_id_primary`(`TRAILER_ID`);
CREATE TABLE `POSTER`(
    `POSTER_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `POSTER_URL` VARCHAR(255) NOT NULL
);
ALTER TABLE
    `POSTER` ADD PRIMARY KEY `poster_poster_id_primary`(`POSTER_ID`);
ALTER TABLE
    `USERS` ADD CONSTRAINT `users_plan_id_foreign` FOREIGN KEY(`PLAN_ID`) REFERENCES `PLAN`(`PLAN_ID`);
ALTER TABLE
    `MOVIE` ADD CONSTRAINT `movie_genre_id_foreign` FOREIGN KEY(`GENRE_ID`) REFERENCES `GENRE`(`GENRE_ID`);
ALTER TABLE
    `MOVIE` ADD CONSTRAINT `movie_trailer_id_foreign` FOREIGN KEY(`TRAILER_ID`) REFERENCES `TRAILER`(`TRAILER_ID`);
ALTER TABLE
    `GENRE` ADD CONSTRAINT `genre_studio_id_foreign` FOREIGN KEY(`STUDIO_ID`) REFERENCES `STUDIO`(`STUDIO_ID`);
ALTER TABLE
    `MOVIE` ADD CONSTRAINT `movie_poster_id_foreign` FOREIGN KEY(`POSTER_ID`) REFERENCES `POSTER`(`POSTER_ID`);